name = "JuliaMapping"
uuid = "6b83013c-2924-4a0a-9bd5-5e672d644478"
version = "0.1.4"
authors = ["technocrat <public@careaga.net>"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Breakers = "e52b5ea0-8122-4946-b8e9-9981f9d15727"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CensusACS = "5cdc1628-db7d-4f1a-9a42-d0831b0d3a5e"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ColorVintner = "b10900d7-caed-426b-ac73-6c8d6f549e92"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordRefSystems = "b46f11dc-f210-4604-bfba-323c1ec968cb"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
FreeTypeAbstraction = "663a7486-cb36-511b-a19d-713bb74d65c9"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GLMNet = "8d5ece8b-de18-5317-b113-243142960cc6"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
GeoInterfaceMakie = "0edc0954-3250-4c18-859d-ec71c1660c08"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Humanize = "7ec9b9c5-1998-51e1-b7fc-fc3590c18259"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NaturalEarth = "436b0209-26ab-4e65-94a9-6526d86fea76"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PointProcesses = "af0b7596-9bb0-472a-a012-63904f2b4c55"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
SpatialIndexing = "d4ead438-fe20-5cc5-a293-4fd39a41b74c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
AbstractTrees = "0.4.5"
AlgebraOfGraphics = "0.11.8"
ArchGDAL = "0.10.10"
Breakers = "0.1.0"
CSV = "0.10.15"
CairoMakie = "0.15.6"
CensusACS = "0.1.0"
Chain = "1.0.0"
ColorSchemes = "3.31.0"
ColorVintner = "1.0.1"
Colors = "0.13.1"
CoordRefSystems = "0.19.0"
Coverage = "1.7.0"
DataFrames = "1.8.0"
DataFramesMeta = "0.7.1"
Dates = "1.11.0"
Distances = "0.10.12"
Distributions = "0.25.122"
Documenter = "1.16.1"
Fontconfig = "0.4.1"
FreeTypeAbstraction = "0.10.8"
GLM = "1.9.0"
GLMNet = "0.7.4"
GeoDataFrames = "0.4.0"
GeoInterfaceMakie = "0.1.9"
GeoJSON = "0.8.4"
GeoMakie = "0.7.15"
GeometryBasics = "0.2.1 - 0.5.10"
Gumbo = "0.8.3"
HTTP = "1.10.19"
Humanize = "1.0.0"
HypothesisTests = "0.11.5"
JSON = "0.21.4"
KernelDensity = "0.6.10"
LinearAlgebra = "1.12.0"
Makie = "0.17.8 - 0.24.6"
NaturalEarth = "0.1.0"
NearestNeighbors = "0.4.22"
Plots = "1.41.1"
Pluto = "0.20.19"
PointProcesses = "0.5.0"
PrettyTables = "3.1.0"
Printf = "1.11.0"
Random = "1.11.0"
SQLite = "1.6.1"
SpatialIndexing = "0.1.6"
StaticArrays = "1.9.15"
Statistics = "1.11.1"
StatsBase = "0.34.6"
XLSX = "0.10.4"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
